default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: smarth-api_development
  username: <%= ENV['DEV_USERNAME']%>
  password: <%= ENV['DEV_PASSWORD']%>
test:
  <<: *default
  database: smarth-api_test
  username: <%= ENV['DEV_USERNAME']%>
  password: <%= ENV['DEV_PASSWORD']%>

production:
  <<: *default
  database: smarth-api_production
  username: <%= ENV['PROD_USERNAME']%>
  password: <%= ENV['PROD_PASSWORD']%>
